core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('shop/', include('shop.urls')),
    path('', lambda request: redirect('quizzes:quiz_list')),  # Is it ok?
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    RegisterView, ProfileView, UserListView, profile_redirect
)


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html',
        next_page='quizzes:quiz_list'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html',
        next_page='quizzes:quiz_list'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('change_password/', ),

    # Profile doesn't need a pk, because it's login required (shows only for themselves). Or not?
    # Or it could use a username insted of pk
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('profile/', profile_redirect, name='profile_redirect'),
    path('', UserListView.as_view(), name='user_list'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from quizzes.models import Quiz, Answer
from shop.models import Color


class User(AbstractUser):
    balance = models.IntegerField(default=0)
    color = models.ForeignKey(to=Color, on_delete=models.CASCADE,
        related_name='users')  # default= ?
    
    colors = models.ManyToManyField(Color)  # Need to add default (fabrik?)
    # User's answers for quiz questions (statistics)
    answers = models.ManyToManyField(Answer, blank=True)
    # Working with answers like that is probably not optimal
    # and we should create a table for statistics or something like that:
    # passed_quizzees = models.ManyToManyField(Quiz)  # ?!
    # but maybe not..

    @property
    def total_points(self) -> int:  # total_score? rating?
        return (self.answers
            .filter(correctanswer__answer_id=models.F('id'))  # the answer is correct
            .aggregate(sum=models.Sum('question__points'))['sum'] or 0)  # get('question__points__sum', 0)

    def is_quiz_passed(self, quiz_id: int) -> bool:
        return self.answers.filter(question__quiz__id=quiz_id).count() > 0
    
    def score_for_quiz(self, quiz_id: int) -> int:
        return (self.answers  # Check needed
            .filter(question__quiz__id=quiz_id,
                    correctanswer__answer_id=models.F('id'))  # the answer is correct
            .aggregate(models.Sum('question__points'))['question__points__sum'] or 0)
        # correctanswer__answer_id=models.F('id') is the same as: 
        # question__correct_answer__answer__id=models.F('id')

    def passed_quizzes(self) -> set[Quiz]:
        return {answer.question.quiz for answer in self.answers.all()}
    
    def passed_quiz_ids(self) -> set[Quiz]:
        return {answer.question.quiz.id for answer in self.answers.all()}
    
    @property
    def passed_quizzes_count(self) -> int:
        # return self.answers.distinct('question__quiz__id')  # It won't work in SQLite
        # This should be a query to DB!
        return len(self.passed_quizzes())
    
    def quiz_answers(self, quiz_id: int) -> list[Answer]:
        """ It returns the user's answers for particular quiz (id) """
        return [answer for answer in self.answers.filter(question__quiz__id=quiz_id)]
    
    # temp (for debugging)
    def _print_passed_quizzes(self) -> None:
        quizzes = self.passed_quizzes()
        for quiz in quizzes:
            print(quiz)
            for question in quiz.questions.all():
                print(f'\t{ question }')
                for answer in question.answers.all():
                    print(f'\t\t{ answer }')
                print(f'\t\t->\t{ question.right_answer }')
                # user's answer
                # There is no any difference between filter() and get in terms of query execution speed.
                print(f'\t\tu ->\t{ self.answers.filter(question__id=question.id).first() }')

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

users/views.py
from collections.abc import Sequence
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.db.models import OuterRef, Sum, Subquery, Count, Case, IntegerField, Value, When, Exists, F#, RawSQL  # Going to use it
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView, ListView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpRequest, HttpResponse

from .forms import CreationForm
from quizzes.models import Question, Answer, CorrectAnswer
from .models import User
# from .models import Color


USER = get_user_model()


class RegisterView(CreateView):
    form_class = CreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ProfileView(LoginRequiredMixin, DetailView):
    login_url = 'users:login'
    model = USER
    template_name = 'users/profile.html'

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        # Validation needed!
        request.user.color = request.user.colors.get(pk=request.POST['choice'])
        request.user.save()
        return redirect('users:profile', pk=request.user.id)


class UserListView(ListView):
    model = USER
    template_name = 'users/user_list.html'
    paginate_by = 20  # It probably shouldn't be hardcoded
    # ordering = []  # to do!

    def get_queryset(self) -> QuerySet[Any]:
        # temporary solution. There should be an ORM query
        return super().get_queryset().raw('\
            SELECT * FROM "users_user"\
            ORDER BY (\
                SELECT SUM("quizzes_question"."points")\
                FROM "quizzes_answer"\
                INNER JOIN "users_user_answers"\
                ON ("quizzes_answer"."id" = "users_user_answers"."answer_id")\
                INNER JOIN "quizzes_correctanswer"\
                ON ("quizzes_answer"."id" = "quizzes_correctanswer"."answer_id")\
                INNER JOIN "quizzes_question"\
                ON "quizzes_answer"."question_id" = "quizzes_question"."id"\
                WHERE ("users_user_answers"."user_id" = "users_user"."id" AND\
                    "quizzes_correctanswer"."answer_id" = ("quizzes_answer"."id"))\
            ) DESC;\
        ')


@login_required(login_url='users:login')
def profile_redirect(request: HttpRequest) -> HttpResponse:
    return redirect('users:profile', pk=request.user.id)

users/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <span class="logo"><a href="{% url 'quizzes:quiz_list' %}">Quizzer</a></span>

        {% if request.user.is_authenticated %}
            <!-- The order of these components should be changed! -->
            <span class="user"><a href="{% url 'users:logout' %}"> Logout </a></span>
            <span class="user"><a
                href="{% url 'users:profile' request.user.id %}"                
                style="
                    border-style: solid;
                    border-width: 1px;
                    border-radius: 10%;
                    border-color:{{ request.user.color.value }};"
            >
                {{ request.user.username }}
            </a></span>
        {% else %}
            <span class="user"><a href="{% url 'users:login' %}"> Login </a></span>
            <span class="user"><a href="{% url 'users:register' %}"> Register </a></span>
        {% endif %}
        <span class="user"><a href="{% url 'users:user_list' %}"> Users </a></span>
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

users/templates/paginator.html
<div class="paginator">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <!-- This isn't good. If there will be a huge amount of pages, this will be bad -->
        {% if page_obj.paginator.num_pages > 1 %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <span class="current">{{ page_obj.number }}</span>
                {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

users/templates/paginator2.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>