core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('shop/', include('shop.urls')),
    path('', lambda request: redirect('quizzes:quiz_list')),  # Is it ok?
]

quizzes/urls.py
from django.urls import path

from .views import QuizListView, QuizView, UserQuizzesView


app_name = 'quizzes'

urlpatterns = [
    path('', QuizListView.as_view(), name='quiz_list'),
    path('<int:pk>/', QuizView.as_view(), name='quiz'),
    path('result/', UserQuizzesView.as_view(), name='user_result')
]

shop/urls.py
from django.urls import path

from .views import ColorListView


app_name = 'shop'

urlpatterns = [
    path('colors/', ColorListView.as_view(), name='colors'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    RegisterView, ProfileView, UserListView, profile_redirect
)


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html',
        next_page='quizzes:quiz_list'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html',
        next_page='quizzes:quiz_list'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('change_password/', ),

    # Profile doesn't need a pk, because it's login required (shows only for themselves). Or not?
    # Or it could use a username insted of pk
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('profile/', profile_redirect, name='profile_redirect'),
    path('', UserListView.as_view(), name='user_list'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from quizzes.models import Quiz, Answer
from shop.models import Color


class User(AbstractUser):
    balance = models.IntegerField(default=0)
    color = models.ForeignKey(to=Color, on_delete=models.CASCADE,
        related_name='users')  # default= ?
    
    colors = models.ManyToManyField(Color)  # Need to add default (fabrik?)
    # User's answers for quiz questions (statistics)
    answers = models.ManyToManyField(Answer, blank=True)
    # Working with answers like that is probably not optimal
    # and we should create a table for statistics or something like that:
    # passed_quizzees = models.ManyToManyField(Quiz)  # ?!
    # but maybe not..

    @property
    def total_points(self) -> int:  # total_score? rating?
        return (self.answers
            .filter(correctanswer__answer_id=models.F('id'))  # the answer is correct
            .aggregate(sum=models.Sum('question__points'))['sum'] or 0)  # get('question__points__sum', 0)

    def is_quiz_passed(self, quiz_id: int) -> bool:
        return self.answers.filter(question__quiz__id=quiz_id).count() > 0
    
    def score_for_quiz(self, quiz_id: int) -> int:
        return (self.answers  # Check needed
            .filter(question__quiz__id=quiz_id,
                    correctanswer__answer_id=models.F('id'))  # the answer is correct
            .aggregate(models.Sum('question__points'))['question__points__sum'] or 0)
        # correctanswer__answer_id=models.F('id') is the same as: 
        # question__correct_answer__answer__id=models.F('id')

    def passed_quizzes(self) -> set[Quiz]:
        return {answer.question.quiz for answer in self.answers.all()}
    
    def passed_quiz_ids(self) -> set[Quiz]:
        return {answer.question.quiz.id for answer in self.answers.all()}
    
    @property
    def passed_quizzes_count(self) -> int:
        # return self.answers.distinct('question__quiz__id')  # It won't work in SQLite
        # This should be a query to DB!
        return len(self.passed_quizzes())
    
    def quiz_answers(self, quiz_id: int) -> list[Answer]:
        """ It returns the user's answers for particular quiz (id) """
        return [answer for answer in self.answers.filter(question__quiz__id=quiz_id)]
    
    # temp (for debugging)
    def _print_passed_quizzes(self) -> None:
        quizzes = self.passed_quizzes()
        for quiz in quizzes:
            print(quiz)
            for question in quiz.questions.all():
                print(f'\t{ question }')
                for answer in question.answers.all():
                    print(f'\t\t{ answer }')
                print(f'\t\t->\t{ question.right_answer }')
                # user's answer
                # There is no any difference between filter() and get in terms of query execution speed.
                print(f'\t\tu ->\t{ self.answers.filter(question__id=question.id).first() }')

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

users/views.py
from collections.abc import Sequence
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.db.models import OuterRef, Sum, Subquery, Count, Case, IntegerField, Value, When, Exists, F#, RawSQL  # Going to use it
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView, ListView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpRequest, HttpResponse

from .forms import CreationForm
from quizzes.models import Question, Answer, CorrectAnswer
from .models import User
# from .models import Color


USER = get_user_model()


class RegisterView(CreateView):
    form_class = CreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class ProfileView(LoginRequiredMixin, DetailView):
    login_url = 'users:login'
    model = USER
    template_name = 'users/profile.html'

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        # Validation needed!
        request.user.color = request.user.colors.get(pk=request.POST['choice'])
        request.user.save()
        return redirect('users:profile', pk=request.user.id)


class UserListView(ListView):
    model = USER
    template_name = 'users/user_list.html'
    paginate_by = 20  # It probably shouldn't be hardcoded
    # ordering = []  # to do!

    def get_queryset(self) -> QuerySet[Any]:
        # temporary solution. There should be an ORM query
        return super().get_queryset().raw('\
            SELECT * FROM "users_user"\
            ORDER BY (\
                SELECT SUM("quizzes_question"."points")\
                FROM "quizzes_answer"\
                INNER JOIN "users_user_answers"\
                ON ("quizzes_answer"."id" = "users_user_answers"."answer_id")\
                INNER JOIN "quizzes_correctanswer"\
                ON ("quizzes_answer"."id" = "quizzes_correctanswer"."answer_id")\
                INNER JOIN "quizzes_question"\
                ON "quizzes_answer"."question_id" = "quizzes_question"."id"\
                WHERE ("users_user_answers"."user_id" = "users_user"."id" AND\
                    "quizzes_correctanswer"."answer_id" = ("quizzes_answer"."id"))\
            ) DESC;\
        ')


@login_required(login_url='users:login')
def profile_redirect(request: HttpRequest) -> HttpResponse:
    return redirect('users:profile', pk=request.user.id)

users/templates/users/colors.html
{% extends "base.html" %}

{% block title %}Colors{% endblock %}

{% block content %}
    <h1>Colors shop</h1>
    <h3>Your balance: {{ request.user.balance }}</h3>

    {% if message %}
        <h3 style="color:rgb(216, 58, 58)">{{ message }}</h3>
    {% endif %}

    {% if object_list %}
        <form method="post" action="{% url 'users:colors' %}">
            {% csrf_token %}
            {% for color in object_list %}
                <div>
                    <button
                        type="submit"
                        class="submit-button2"
                        name="color_id"
                        value="{{ color.id }}"
                        
                        {% if request.user.is_authenticated and color in request.user.colors.all %}
                            disabled
                        {% endif %}
                    >
                        buy
                    </button>
                        
                    <!-- Color:  -->
                    <span style="
                        color: {{ color.value }};
                        background-color: {{ color.value }};
                        border-style: solid;
                        border-color: black;
                        border-width: 1px;"
                    >
                        COLOR
                    </span>
                    {{ color.name }}, 
                    price: <strong>{{ color.price }}</strong>
                </div>
            {% endfor %}
            
            <!-- <br><button type="submit" class="submit-button">Buy</button> -->
        </form>
    {% else %}
        There are no colors yet.
    {% endif %}
    
    <br><a href="{% url 'users:profile' request.user.pk  %}">Go to profile</a>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log in"></p>
    </form>
    <p>
        Don't have an account? Register <a href="{% url 'users:register' %}">here</a>
    </p>
{% endblock %}

users/templates/users/logout.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log in"></p>
    </form>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}{{ request.user.username }} profile{% endblock %}

{% block content %}
    <h1>Welcome, {{ request.user.username }}</h1>
    
    <p>
        <a href="{% url 'quizzes:user_result' %}">
            Passed quizzes: {{ request.user.passed_quizzes_count }}
        </a>
    </p>

    <p>Points: {{ request.user.total_points }}</p>
    <p>Balance: {{ request.user.balance }}</p>

        <p>
            {% if object.colors.all %}
                <form action="{% url 'users:profile' request.user.id %}" method="post">
                    {% csrf_token %}
                    Color: 
                    <select type="submit" onchange="this.form.submit()" name="choice"
                        style="background-color: {{ request.user.color.value }};"
                    >
                        {% for color in object.colors.all %}
                            <option
                                value="{{ color.pk }}" 
                                style="background-color: {{ color.value }};"
                                {% if object.color.pk == color.pk %}selected{% endif %}>
                                {{ color.name }}
                            </option>
                        {% endfor %}
                    </select>
                    <!-- <button type="submit" class="submit-button2">apply</button> -->
                </form>
            {% else %}
                Color: 
                <select>
                    <option value="0">no colors</option>
                </select>
            {% endif %}
            
        </p>


    <p><a href="{% url 'shop:colors' %}">Buy colors</a></p>
    <!-- <p><a href="">Change password</a></p> -->
    <p><a href="{% url 'users:logout' %}">Logout</a></p>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

    <h1>Registrer</h1>
    <p>Please, use the following form to create an account:</p>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create"></p>
    </form>
    <p>
        Already have an account? Login <a href="{% url 'users:login' %}">here</a>
    </p>

{% endblock %}

users/templates/users/user_list.html
{% extends "base.html" %}

{% block title %}Users{% endblock %}

{% block content %}
    <h1>Users</h1>
    <p>
        Number of users: {{ object_list|length }}
    </p>
    {% if object_list %}
        {% for user in page_obj %}
            <p>
                <strong style="
                    border-style: solid;
                    border-width: 2px;
                    border-color: {{ user.color.value }};"
                >
                    {{ user.username }}
                </strong>
                passed quizzes: {{ user.passed_quizzes|length }}, 
                total points: {{ user.total_points }}
            </p>
        {% endfor %}
    {% else %}
        There are no users yet.
    {% endif %}

    {% include "paginator.html" with page_obj=page_obj %}
    
    <br><a href="{% url 'quizzes:quiz_list' %}">Go to quizzes</a>
{% endblock %}