core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('shop/', include('shop.urls')),
    path('', lambda request: redirect('quizzes:quiz_list')),  # Is it ok?
]

shop/urls.py
from django.urls import path

from .views import ColorListView


app_name = 'shop'

urlpatterns = [
    path('colors/', ColorListView.as_view(), name='colors'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    RegisterView, ProfileView, UserListView, profile_redirect
)


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html',
        next_page='quizzes:quiz_list'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html',
        next_page='quizzes:quiz_list'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('change_password/', ),

    # Profile doesn't need a pk, because it's login required (shows only for themselves). Or not?
    # Or it could use a username insted of pk
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('profile/', profile_redirect, name='profile_redirect'),
    path('', UserListView.as_view(), name='user_list'),
]

shop/models.py
from django.db import models


class Color(models.Model):
    name = models.CharField(verbose_name='Color name', default='', unique=True,
                            max_length=32)
    value = models.CharField(default='rgba(255,255,255,1)', max_length=64)  # unique=?
    price = models.IntegerField(default=0)
    # description = models.CharField(default='', max_length=512)

    def __str__(self) -> str:
        return f"Color: {self.name} ({self.value}), price: {self.price}"

shop/views.py
from typing import Any

from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse

from .models import Color


class ColorListView(LoginRequiredMixin, ListView):  # Should it be a FormView?
    login_url = 'users:login'
    model = Color
    template_name = 'shop/colors.html'
    # paginate_by = 20  # Should it be hardcoded?
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        color = Color.objects.get(pk=int(request.POST['color_id']))
        user = request.user
        if user.balance < color.price:
            return render(request, self.template_name, {
                'message': 'No money, no honey',
                'object_list': self.get_queryset(),  # This is probably not good!
                # 'page_obj': self.get_paginator(self.get_queryset(), 20),#self.get_paginate_by()),
            })
            # This won't work..
            # return self.render_to_response({
            #     'message': 'Not enough money',
            #     'object_list': self.get_queryset(),
            # })#, **kwargs)
        user.balance -= color.price
        user.colors.add(color)
        user.save()
        return redirect('shop:colors')

shop/templates/shop/colors.html
{% extends "base.html" %}

{% block title %}Colors{% endblock %}

{% block content %}
    <h1>Colors shop</h1>
    <h3>Your balance: {{ request.user.balance }}</h3>

    {% if message %}
        <h3 class="message">{{ message }}</h3>
    {% endif %}

    {% if object_list %}
        <form method="post" action="{% url 'shop:colors' %}">
            {% csrf_token %}
            {% for color in object_list %}
                <div>
                    <button
                        type="submit"
                        class="submit-button2"
                        name="color_id"
                        value="{{ color.id }}"
                        
                        {% if request.user.is_authenticated and color in request.user.colors.all %}
                            disabled
                        {% endif %}
                    >
                        buy
                    </button>
                        
                    <!-- Color:  -->
                    <span style="
                        color: {{ color.value }};
                        background-color: {{ color.value }};
                        border-style: solid;
                        border-color: black;
                        border-width: 1px;"
                    >
                        COLOR
                    </span>
                    {{ color.name }}, 
                    price: <strong>{{ color.price }}</strong>
                </div>
            {% endfor %}
            
            <!-- <br><button type="submit" class="submit-button">Buy</button> -->
        </form>
    {% else %}
        There are no colors yet.
    {% endif %}

    <br>
    <!-- { include "paginator.html" with page_obj=page_obj } -->
    
    <br><a href="{% url 'users:profile' request.user.pk  %}">Go to profile</a>
{% endblock %}